koding/kite

- heartbeat.go
Normally registration is forever, until you stop the APP. However if it
fails once to send an heartbeat and Kontrol sends a `registerAgain`, it
would try to re-register it. The problem here is, the registration part
is done once only. So if something goes wrong and the registration
fails, we need to try to register until we are again the loop.
By changing the RegisterHTTP to RegisterHTTPForever, it'll try to
register until it's successfull. Once registered, the heartbeat will be
starting again.
> heartbeat: fix not re-registering when registerHTTP fails

- kontrol/kontrol/main.go
The multiconfig require for postgres username/dbname seemingly makes it impossible to utilize the KONTROL_STORAGE env variable for etcd without first setting those
> Config for KONTROL_STORAGE

- method.go
- method_test.go
- request.go
We have a new method called `Throttle()` which can be used for any existing method. Instead of:
```go
k.Handle("info", infoHandler)
```
we can use
```go
k.Handle("info", infoHandler).Throttle(30, time.Second) // rate limit to 30 req/s
```
> Add throttling for individual methods

- method.go
- method_test.go
Based on the conversation with @rogpeppe here: https://twitter.com/rogpeppe/status/570224998759079936
Basically previously it was using the Quantum option which would fill the bucket immediately. It would encourage clients to make burst calls. Now there is a consistent flow.
> method: improve throttle

- server.go
Problem:
I have a kite that is configured to listen on random port (0). 
I need to register this kite to Kontrol instance but first I need to know the port number that the kite is listening on.
Currently there is no way of getting the auto-assigned port number.
```go
package main
import (
"net/url"
"github.com/koding/kite"
)
func main() {
k := kite.New("first", "1.0.0")
k.Config.Port = 0 // auto-assign
k.Register(&url.URL{Scheme: "http", Host: "127.0.0.1:?????", Path: "/kite"})
k.Run()
}
```
This PR solves the problem by adding a Port() method to kite that returns the auto-assigned port number.
> add Kite.Port() method

- kontrol/handlers.go
- kontrol/kontrol.go
* This allows us to pass additional arguments to authMachine.
* `authType` is a new argument, which the authMachine function can use
it to decide on how to make the authentication
> kontrol: make machineAuthenticate more flexible

- kontrol/handlers.go
* For `password` authentication type we already validate the username which is passed via `r.Client.Kite.Username`.
> kontrol: use authenticated username

- heartbeat.go
- kontrol/handlers.go
- kontrol/http.go
- kontrol/kontrol.go
Two changes in this PR:
1. We now trim any whitespace when adding or retrieving keys. Otherwise it's get difficult to retrieve as a single whitespace might cause the key to be not found
2. HTTP based registration was broken, fixed and synced it with XHR and WebSocket based one.
> kontrol: take care of multi keys for HTTP based registration

- handlers.go
code.google.com is shutting down. Now it changed to golang.org instead.
> Change go crypto package from code.google.com to golang.org.

- heartbeat.go
- kite.go
The existing Backoff library is being used to backoff repeated attempts
to from RegisterHTTPForever(). The backoff numbers have been tweaked to
be generous, as discussed with Cihangir.
> backoff: Added backoff to Kite.RegisterHTTPForever()

- kontrol/kontrol/main.go
- kontrol/postgres.go
Added an option to kontrol to specify the postgres `connect_timeout` option, defaulting to 20 seconds.
cc @cihangir @fatih
> postgres: Added postgres timeout to kontrol

- heartbeat.go
The backoff and variance was proving to be too small with any sizable amount of load, so this PR increases the backoff time, and allows the variance to be more meaningfully random given the larger max backoff.
cc @fatih
> backoff: Increased backoff to a maximum of 5m, with an Initial of 30s

- kontrol/etcd.go
when the ttl expires, update will no longer work due to etcd returning a key not found error. try to add the kite again, which gets things working again. without this, kite keeps retrying and failing forever, and the service needs to be restarted for it to work.
> kontrol: re-add when update fails

- kontrolclient.go
In order to allow applications to implement their own application specific Kontrol calls, a TellKontrolWithTimeout method has been added.
cc @fatih
> Added TellKontrolWithTimeout Kite Method

- client.go
- kite.go
Due to `Kite.kontrol.Client` not being exposed _(or existing before
being dialed)_, api users were unable to set the `Client.ClientFunc`
field for the Kontrol Client.
This commit simply adds a ClientFunc field onto the Kite itself, which
will also be used as the default ClientFunc value for any Client's created from
the Kite - including `Kite.kontrol.Client`.
cc @rjeczalik @cihangir
> kite: Added ClientFunc on Kite struct

- Makefile
- kontrolclient.go
- tokenrenewer.go
`tokenrenewer` was reported to panic while handling disconnect signal
with the following stacktrace:
panic: close of closed channel
goroutine 282305 [running]:
github.com/koding/kite.func·034()
github.com/koding/kite/tokenrenewer.go:64 +0x2e
github.com/koding/kite.func·006()
github.com/koding/kite/client.go:498 +0x4f
github.com/koding/kite.(*Client).callOnDisconnectHandlers(0xc20aaf9a40)
github.com/koding/kite/client.go:499 +0xdc
github.com/koding/kite.(*Client).run(0xc20aaf9a40)
github.com/koding/kite/client.go:290 +0x13a
created by github.com/koding/kite.(*Client).dialForever
github.com/koding/kite/client.go:255 +0xc1
This PR:
- ensures the handlers are registered only once as multiple disconnect handlers
would start renew loop multiple times
- signals disconnection events by sending …
> TMS-2624 tokenrenewer: add 2 defensive checks

- dnode/partial_test.go
- dnode/scrub.go
- dnode/scrub_test.go
Go 1.6 introduced a breaking change in "reflect" package(golang issue #12367).
This broke dnode.Scrubber.Scrub method that was using reflect.Value.Interface
method to collect callbacks. Since go1.6 you cannot get an interface to private
embedded structs so, if you passed embedded struct to Scrub method, it would
panic.
This commit refactors Scrub method and makes it valid in >=go1.6.
Additionally, there is a minor fix which discards JSON field tag options when
they are provided.
> dnode: rework scrubbing to make it work on go1.6+  - fixes #149

- appveyor.yml
- dnode/scrubber.go
- systeminfo/systeminfo_test.go
- systeminfo/systeminfo_windows.go
systeminfo package is implemented in all major platforms except Windows. This PR fixes this.
> systeminfo: add windows implementation

- bug_test.go
- client.go
- server.go
We rely on this behaviour in one of our internal tests.
There's still room for further improvement by merging runloop and sendHub into one control goroutine, thus making the session state easier to control.
> kite: make consecutive dials work

- config/config.go
- kite.go
- kontrol/kontrol.go
- request.go
Fixes:
```
2016-07-04 12:05:22 [klient] ERROR    Error in token. Token will not be renewed when it expires: Cannot parse token: Token used before issued
```
When klient and kontrol were in different timezones and their diff > leeway (by default always).
jwt-go 2.0 did use local time as does version 3.0, so renewing either did not worked at all or the tokens started to be validated right now - I have did not dig that deep.
> kite: always use UTC timezone for tokens

- client.go
- heartbeat.go
- kontrol/kontrol.go
deps: https://github.com/koding/kite/pull/171
The default behaviour for go1.4 scheduler is to execute incoming
callback in order they were received. That applies to small group of
short-lived callbacks that don't do any I/O.
go1.5+ scheduler is more reentrant, which makes callback execution
out-of-order. This breaks existing code that relies on go1.4 scheduler
behaviour.
This PR adds ConcurrentCallbacks field to client which is false by
default to restore go1.4 behaviour.
If you rely on your callbacks being done asynchronously (e.g. you're
doing heavy computations in them) set ConcurrentCallbacks to true
for each your *kite.Client value.
> kite/client: make callback execution synchronous

- client.go
- kite_test.go
- sockjsclient/xhr.go
When underlying streaming transport (session) was unexpectedly
closed, client hangs when no timeout was set.
We should instead expect underlying transport to fail and forward
the error to the caller instead, so it does not hang, no matter
whether timeout was used or not.
> klient: fix client deadlock on session failure

- kite_test.go
Addresses [0]. Ensures callbacks are executed in-order by default.
[0] https://github.com/koding/kite/pull/172#issuecomment-234893129
> kite: add a test for concurrent callbacks

- errors.go
- kite.go
- kite_test.go
- method.go
- method_test.go
- request.go
- sockjsclient/sockjsclient.go
- sockjsclient/xhr.go
- utils/utils.go
Hey @cihangir!
The purpose of this PR is to:
- make Client mark each request with unique ID
- add FinalFunc to Client, which purpose is roughly the same as PostHandler, with the only difference it is executed also on failures and it's capable of overwriting / decorating handler's response
The above extensions to kite are needed to extend per-request logging for klient kite.
Please take a look.
> kite: add ID for every request / add final handlers

- kite.go
`sockjsHandler` creates a new `kite.Client` object for each `sockjs.Session`. Handler and session end their life when blocking `readLoop()` method returns. This means that created `kite.Client` is no longer needed. However, it can't be GC because `sendHub()` still waits for incoming data from `readLoop()` which, as was written above, already returned. 
This change closes created `kite.Client` when it's no longer needed. Closing it will also stop `sendHub()` go-routine.
> kite: don't leak sendHub goroutine when client's readLoop ends

- sockjsclient/xhr.go
when the XHR session is closed, there is no way to drain `<-chan doResult` created by `do()`
[method](https://github.com/koding/kite/compare/xhr_session_leak_fix?expand=1#diff-531282dec6b6ed573b67713e0de77f94R113) because `Recv()` internal loop is already aborted.
This PR makes returned `doResult` channel buffered, thus, it will prevent go-routine leaks after session is closed.
> sockjsclient: do not block on sending do() method Result

- config/config.go
This change is already implemented in vendored `koding/kite` [package](https://github.com/koding/koding/blob/master/go/src/vendor/github.com/koding/kite/config/config.go#L152). Provided PR makes `koding/kite` and vendored kite from `koding/koding` consistent.
This is a non-breaking change.
> config: make ReadToken public

- .travis.yml
- client.go
- handlers.go
- kite.go
- kite_test.go
- tokenrenewer.go
A number of changes:
- kite: ignore panics in handlers
Makes (*Kite).callOn* method impelementations on a par with *Client ones.
- kite: fix panic ignoring 
The recover method should be called from within a function, not be a deferred function itself.
- tokenrenewer: improve fix for a panic #187 
The error returned by kontrol is different than
the ErrKitNotAvailable, that's why the assert
on message content.
Moreover the renewLoop lifetime handling was
improved:
- "kite not found" errors do not cause the goroutine
to exit - they're just ignored instead, in case
a heartbeat went through and kite was again
registered to kontrol without local Kite knowing it
(no OnConnect handler gets executed then); this
is an assumption, I did not manage to write a test
to prove it
- we wait for previous …
> tokenrenewer: improve fix for a panic #187

- .travis.yml
- appveyor.yml
- client.go
- config/config.go
- config/config_test.go
- heartbeat.go
- kite.go
- kite_test.go
- sockjsclient/export_test.go
- sockjsclient/sockjsclient.go
- sockjsclient/sockjsclient_test.go
- sockjsclient/xhr.go
- tunnelproxy/proxy.go
- tunnelproxy/tunnel.go
This PR reworks connection configuration part of the kite package.
Currently:
1) it is not possible to configure SockJS server handler
2) client can be configured via setting the following fields:
- (*Kite).ClientFunc
- (*Client).ClientFunc
- (*Client).ReadBufferSize
- (*Client).WriteBufferSize
- (*DialOptions).ReadBufferSize
- (*DialOptions).WriteBufferSize
- (*DialOptions).Timeout
3) it is not possible to configure websocket client (compression, response limit etc.)
This PR unifies the configuration by adding:
1) (*config.Config).SockJS
2) (*config.Config).XHR + external sockjs.WebSocketUpgrader (https://github.com/igm/sockjs-go/pull/56)
3) (*config.Config).Websocket
All the changes are done in a backward-compatible way, with deprecation documentation in appropriate places.
Please take …
> kite: improve client/server connection configuration

- kontrol/handlers.go
- kontrol/kontrol.go
- kontrol/kontrol_test.go
- protocol/protocol.go
The "getToken" method will always return the same token until
it has expired.
The Force parameter forces Kontrol to generate new token,
even if the old one is not expired, at least from Kontrol's
perspective.
> kontrol: add Force parameter to get new token

- client.go
- config/config.go
- config/transport.go
- kontrol/kontrol_test.go
- kontrolclient.go
- sockjsclient/sockjsclient.go
- sockjsclient/xhr.go
- sockjsclient/xhr_test.go
This PR:
- adds config.Auto
- adds config.Config.Timeout
- handles poll timeouts during reading XHR response body
- interrupts readloop (effectively stops session) if send failed due to closed session
Please take a look.
> kite/client: improve resilience

- config/config.go
- server.go
Currently (*kite.Kite).Run() uses default HTTP server for serving
requests. If a custom http.Server (e.g. with adjusted
timeouts etc.) is needed, a Serve field can be used to provide
custom implementation.
In particular this field is needed to disable HTTP2 server for
cmd/tunnelserver in order to fix koding/koding#11269.
> config: add Serve field

- kontrol/etcd.go
A change made to the net/url library in go 1.8 causes a panic when
starting kontrol:
panic: parse 127.0.0.1:4001: first path segment in URL cannot contain colon
This is caused by the fact that net/url no longer considers
"127.0.0.1:4001" a valid URL because the specification allows for dots
in the schema-part of the URL.
* https://github.com/golang/go/issues/19297
> Fixes breaking change done in net/url

- .travis.yml
- kontrol/_watcher.go
- kontrol/etcd.go
- kontrol/node.go
https://github.com/coreos/go-etcd/etcd has been deprecated in favor
of https://github.com/coreos/etcd/client. This patch updates kontrol
to use the supported etcd client library.
> kontrol: Use supported etcd client library

- client.go
- examples/math/math-kite/math.go
- kite.go
- kite_test.go
- method_test.go
- request.go
There is a common scenario, where a kite handler expects a callback sent from a client, just to start a long-running goroutine and feed information to client via that callback.
We want to have a mean to terminate that long-running goroutine when client disconnect, in order to clean resources.
This PR makes the (*kite.Request).Context a proper context.Context value, which is canceled upon client being disconnected.
> kite: expose client lifetime information to kite handler

- Gopkg.lock
- Gopkg.toml
- kite.go
- kite_test.go
- kitetest/kitetest.go
- kontrol/bench_test.go
- kontrol/kontrol.go
- kontrol/kontrol_test.go
- testutil/testutil.go
Closes #218.
Closes #219.
Closes #220.
> kite: adapt code to latest go.uuid version
